[package]
name = "heaters"
version = "0.1.0"
authors = ["SeongChan Lee <foriequal@gmail.com>"]

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
num_cpus = "1.0"
cgmath = "*"
rand = "*"
systemstat = "*"
parking_lot = "*"